# Generated by Django 5.0.7 on 2024-08-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breaker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="completion",
            name="gate",
            field=models.IntegerField(default=1),
        ),
    ]
