# Generated by Django 5.0.7 on 2024-08-05 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breaker", "0003_attempt_curr_ans"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attempt",
            old_name="stage",
            new_name="gate",
        ),
    ]
